# Generated by Django 4.1.6 on 2023-02-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_rename_boolean_trainer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
