# Generated by Django 4.1.6 on 2023-03-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_trainer_hours_trainer_price_trainer_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
