# Generated by Django 4.1.6 on 2023-03-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_author_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
